{% set name = "scitokens" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scitokens-{{ version }}.tar.gz
  sha256: d6347d5f9e0abbe9d22e77027a2563c3d5dec5db66d43d30a507dc2ee3251421

build:
  number: 0
  noarch: python
  entry_points:
    - scitokens-admin-create-key=scitokens.tools.admin_create_key:main
    - scitokens-admin-create-token=scitokens.tools.admin_create_token:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - cryptography
    - pyjwt >=2.0.0
    - python >=3.6
    - six

test:
  requires:
    - pip
    - pytest
  source_files:
    - tests/
  commands:
    # check requirements
    - python -m pip check
    # run test suite
    - python -m pytest -ra -v tests/
    # sanity check entry points
    - scitokens-admin-create-key --help
    - scitokens-admin-create-token --help

about:
  home: https://scitokens.org
  dev_url: https://github.com/scitokens/scitokens.git
  summary: SciToken reference implementation library
  license: Apache-2.0
  license_file: LICENSE
  description: |
    This library aims to be a reference implementation of the
    SciTokens\' JSON Web Token (JWT) token format.

    SciTokens is built on top of the PyJWT and cryptography libraries.
    We aim to provide a safe, high-level interface for token manipulation,
    avoiding common pitfalls of using the underling libraries directly.

extra:
  recipe-maintainers:
    - duncanmmacleod
