{% set name = "scitokens" %}
{% set version = "1.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scitokens-{{ version }}.tar.gz
  sha256: d215091b5a66d8cf37d386602495e93f347646f132469091ca44148683193c4e

build:
  number: 0
  noarch: python
  entry_points:
    - scitokens-admin-create-key=scitokens.tools.admin_create_key:main
    - scitokens-admin-create-token=scitokens.tools.admin_create_token:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - cryptography
    - pyjwt >=1.6.1
    - python >=3.5
    - setuptools

test:
  requires:
    - pip
    - pytest
  source_files:
    - tests/
  commands:
    # check metadata
    - python -m pip check scitokens
    - python -m pip show scitokens
    # run test suite
    - python -m pytest -ra -v tests/
    # sanity check entry points
    - scitokens-admin-create-key --help
    - scitokens-admin-create-token --help

about:
  home: https://scitokens.org
  dev_url: https://github.com/scitokens/scitokens.git
  doc_url: https://scitokens.readthedocs.io
  summary: SciToken reference implementation library
  license: Apache-2.0
  license_file: LICENSE
  description: |
    This library aims to be a reference implementation of the
    SciTokens\' JSON Web Token (JWT) token format.

    SciTokens is built on top of the PyJWT and cryptography libraries.
    We aim to provide a safe, high-level interface for token manipulation,
    avoiding common pitfalls of using the underling libraries directly.

extra:
  recipe-maintainers:
    - duncanmmacleod
